export interface Recipe {
  id: string;
  name: string;
  emoji: string;
  category: string;
  cuisine: string;
  cookTime: number; // minutes
  difficulty: "Easy" | "Medium" | "Hard";
  description: string;
  tags: string[];
  gradient: string;
  calories: number;
  servings: number;
}

export const RECIPES: Recipe[] = [
  {
    id: "1",
    name: "Thai Basil Chicken",
    emoji: "🌶️",
    category: "Savory",
    cuisine: "Asian",
    cookTime: 25,
    difficulty: "Medium",
    description: "Fragrant basil, spicy chilies, tender ground chicken over jasmine rice. A weeknight hero that's ready in under 30 minutes.",
    tags: ["Spicy", "High Protein", "Asian"],
    gradient: "from-orange-500 to-red-500",
    calories: 420,
    servings: 2,
  },
  {
    id: "2",
    name: "Honey Garlic Salmon",
    emoji: "🐟",
    category: "Healthy",
    cuisine: "American",
    cookTime: 20,
    difficulty: "Easy",
    description: "Glazed salmon fillet with sticky honey garlic sauce. Ready in 20 minutes with minimal cleanup — perfect for weeknights.",
    tags: ["Omega-3", "Quick", "Kid-Friendly"],
    gradient: "from-pink-500 to-rose-500",
    calories: 380,
    servings: 2,
  },
  {
    id: "3",
    name: "Creamy Mushroom Pasta",
    emoji: "🍝",
    category: "Comfort",
    cuisine: "Italian",
    cookTime: 30,
    difficulty: "Easy",
    description: "Silky mushroom cream sauce tossed with al dente pasta. Rich, earthy, and deeply satisfying without any meat.",
    tags: ["Vegetarian", "Comfort", "Italian"],
    gradient: "from-amber-600 to-yellow-500",
    calories: 520,
    servings: 3,
  },
  {
    id: "4",
    name: "Korean BBQ Beef Bowl",
    emoji: "🥩",
    category: "Savory",
    cuisine: "Korean",
    cookTime: 35,
    difficulty: "Medium",
    description: "Thinly sliced beef marinated in soy, sesame, and ginger over steamed rice with pickled vegetables.",
    tags: ["Korean", "High Protein", "Meal Prep"],
    gradient: "from-red-600 to-orange-500",
    calories: 560,
    servings: 2,
  },
  {
    id: "5",
    name: "Avocado Toast Supreme",
    emoji: "🥑",
    category: "Healthy",
    cuisine: "American",
    cookTime: 5,
    difficulty: "Easy",
    description: "Smashed avocado on sourdough toast topped with everything bagel seasoning, cherry tomatoes, and a poached egg.",
    tags: ["Breakfast", "Healthy Fats", "Quick"],
    gradient: "from-green-500 to-emerald-600",
    calories: 350,
    servings: 1,
  },
  {
    id: "6",
    name: "Chicken Tikka Masala",
    emoji: "🍛",
    category: "Savory",
    cuisine: "Indian",
    cookTime: 45,
    difficulty: "Medium",
    description: "Tender chicken in a rich, aromatic tomato-cream sauce with warm spices. Serve with fluffy naan and basmati rice.",
    tags: ["Indian", "Spicy", "Creamy"],
    gradient: "from-orange-600 to-amber-500",
    calories: 480,
    servings: 4,
  },
  {
    id: "7",
    name: "Caesar Salad with Crispy Shrimp",
    emoji: "🥗",
    category: "Healthy",
    cuisine: "American",
    cookTime: 15,
    difficulty: "Easy",
    description: "Classic romaine caesar salad topped with crispy pan-seared shrimp, homemade croutons, and fresh parmesan.",
    tags: ["Salad", "Light", "Seafood"],
    gradient: "from-teal-500 to-cyan-500",
    calories: 310,
    servings: 2,
  },
  {
    id: "8",
    name: "Margherita Flatbread Pizza",
    emoji: "🍕",
    category: "Comfort",
    cuisine: "Italian",
    cookTime: 15,
    difficulty: "Easy",
    description: "Crispy flatbread topped with San Marzano tomato sauce, fresh mozzarella, and hand-torn basil leaves.",
    tags: ["Vegetarian", "Pizza", "Italian"],
    gradient: "from-red-500 to-pink-500",
    calories: 410,
    servings: 2,
  },
  {
    id: "9",
    name: "Mango Coconut Overnight Oats",
    emoji: "🥭",
    category: "Sweet",
    cuisine: "Fusion",
    cookTime: 5,
    difficulty: "Easy",
    description: "Creamy oats soaked overnight in coconut milk, topped with fresh mango, toasted coconut flakes, and honey.",
    tags: ["Breakfast", "Vegan", "No-Cook"],
    gradient: "from-yellow-400 to-orange-400",
    calories: 290,
    servings: 1,
  },
  {
    id: "10",
    name: "Sushi Bake Bowl",
    emoji: "🍱",
    category: "Savory",
    cuisine: "Japanese",
    cookTime: 30,
    difficulty: "Medium",
    description: "Deconstructed sushi bake with seasoned rice, creamy crab mixture, furikake, and spicy mayo drizzle.",
    tags: ["Japanese", "Trending", "Seafood"],
    gradient: "from-indigo-500 to-violet-500",
    calories: 490,
    servings: 3,
  },
  {
    id: "11",
    name: "Shakshuka",
    emoji: "🍳",
    category: "Savory",
    cuisine: "Middle Eastern",
    cookTime: 20,
    difficulty: "Easy",
    description: "Eggs poached in a spiced tomato and pepper sauce. Serve with crusty bread for a brunch that impresses everyone.",
    tags: ["Vegetarian", "Brunch", "One Pan"],
    gradient: "from-red-600 to-orange-600",
    calories: 280,
    servings: 2,
  },
  {
    id: "12",
    name: "Butter Chicken Tacos",
    emoji: "🌮",
    category: "Fusion",
    cuisine: "Fusion",
    cookTime: 40,
    difficulty: "Medium",
    description: "Indian-Mexican fusion: butter chicken filling in warm tortillas with mango salsa, cilantro, and cooling raita.",
    tags: ["Fusion", "Trending", "Spicy"],
    gradient: "from-orange-500 to-yellow-500",
    calories: 440,
    servings: 3,
  },
  {
    id: "13",
    name: "Chocolate Lava Cake",
    emoji: "🍫",
    category: "Sweet",
    cuisine: "French",
    cookTime: 25,
    difficulty: "Medium",
    description: "Warm chocolate cake with a molten liquid center. Serve immediately with vanilla ice cream for full effect.",
    tags: ["Dessert", "Chocolate", "Impressive"],
    gradient: "from-amber-900 to-brown-600",
    calories: 380,
    servings: 4,
  },
  {
    id: "14",
    name: "Vietnamese Pho",
    emoji: "🍜",
    category: "Savory",
    cuisine: "Vietnamese",
    cookTime: 60,
    difficulty: "Hard",
    description: "Rich bone broth simmered for hours with star anise and cinnamon. Topped with rice noodles and fresh herbs.",
    tags: ["Vietnamese", "Comfort", "Weekend"],
    gradient: "from-amber-700 to-orange-600",
    calories: 320,
    servings: 4,
  },
  {
    id: "15",
    name: "Greek Mezze Platter",
    emoji: "🫒",
    category: "Healthy",
    cuisine: "Mediterranean",
    cookTime: 15,
    difficulty: "Easy",
    description: "Hummus, tzatziki, stuffed grape leaves, feta, olives, and warm pita. Perfect for sharing or grazing.",
    tags: ["Mediterranean", "Vegetarian", "Sharing"],
    gradient: "from-cyan-500 to-blue-500",
    calories: 450,
    servings: 4,
  },
  {
    id: "16",
    name: "Birria Ramen",
    emoji: "🫕",
    category: "Fusion",
    cuisine: "Fusion",
    cookTime: 90,
    difficulty: "Hard",
    description: "Mexican birria beef in Japanese ramen broth — the ultimate fusion comfort food taking TikTok by storm.",
    tags: ["Fusion", "Viral", "Weekend"],
    gradient: "from-red-700 to-rose-600",
    calories: 620,
    servings: 3,
  },
  {
    id: "17",
    name: "Banana Pancakes",
    emoji: "🥞",
    category: "Sweet",
    cuisine: "American",
    cookTime: 15,
    difficulty: "Easy",
    description: "Fluffy pancakes with mashed banana batter. Naturally sweet, served with maple syrup and fresh berries.",
    tags: ["Breakfast", "Kid-Friendly", "Sweet"],
    gradient: "from-yellow-400 to-amber-500",
    calories: 310,
    servings: 2,
  },
  {
    id: "18",
    name: "Spicy Tuna Poke Bowl",
    emoji: "🐠",
    category: "Healthy",
    cuisine: "Hawaiian",
    cookTime: 10,
    difficulty: "Easy",
    description: "Fresh ahi tuna marinated in sesame soy sauce over sushi rice with edamame, cucumber, and spicy mayo.",
    tags: ["Hawaiian", "Raw", "Healthy"],
    gradient: "from-rose-500 to-pink-600",
    calories: 420,
    servings: 1,
  },
];
